version: 2
updates:
  - package-ecosystem: docker
    directory: /tools/releaseBuild/Images/microsoft_powershell_ubuntu16.04
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /tools/releaseBuild/Images/microsoft_powershell_ubuntu18.04
    schedule:
      interval: daily
