parameters:
  vmImage: 'ubuntu-16.04'
  parentJobs: []

jobs:
- job: push
  pool:
    vmImage: ${{ parameters.vmImage }}

  displayName: Push to Store

  variables:
    ReleaseTag: hotfix/default

  dependsOn:
    ${{ parameters.parentJobs }}

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      downloadType: specific
      itemPattern: '**/*.snap'

  - powershell: |
      [string]$Branch=$env:BUILD_SOURCEBRANCH,
      [string]$Variable='ReleaseTag'
      $branchOnly = $Branch -replace '^refs/heads/';
      $branchOnly = $branchOnly -replace '[_\-]'
      if($branchOnly -eq 'master' -or $branchOnly -like '*dailytest*')
      {
          Write-verbose "release branch:" -verbose
          $releaseTag = 'edge'
          $vstsCommandString = "vso[task.setvariable variable=$Variable]$releaseTag"
          Write-Verbose -Message "setting $Variable to $releaseTag" -Verbose
          Write-Host -Object "##$vstsCommandString"
      }
      else
      {
          Write-verbose "non-release branch" -verbose
          # Branch is named <previewname>
          $releaseTag = "hotfix/$branchOnly"
          $vstsCommandString = "vso[task.setvariable variable=$Variable]$releaseTag"
          Write-Verbose -Message "setting $Variable to $releaseTag" -Verbose
          Write-Host -Object "##$vstsCommandString"
      }
    displayName: Set ReleaseTag Variable

  - powershell: |
      sudo apt-get update
      sudo apt-get install -y snapcraft
    displayName: 'Install snapcraft'

  - powershell: |
      $loginFile='./snapstore.login'

      '$(SNAPLOGIN)' | base64 --decode --ignore-garbage > $loginFile
      snapcraft login --with $loginFile
      rm $loginFile
    displayName: 'snapcraft login'

  - powershell: |
      $snaps = Get-ChildItem $(System.ArtifactsDirectory)/*.snap -recurse -File | Select-Object -ExpandProperty FullName

      foreach($snap in $snaps)
      {
        snapcraft push --release $(ReleaseTag) $snap
      }
    displayName: 'snapcraft push'

  - powershell: |
      snapcraft logout
    displayName: 'snapcraft logout'
    condition: always()

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'


