parameters:
  vmImage: 'ubuntu-16.04'
  matrix:

jobs:

- job: build
  strategy:
    matrix:
      ${{ parameters.matrix }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
  - powershell: 'dir env:'
    displayName: 'Capture Environment'

  - powershell: |
      $releaseTagName = switch('$(channel)') {
        'stable' {
          'StableReleaseTag'
        }
        'preview' {
          'PreviewReleaseTag'
        }
        default {
          'PreviewReleaseTag'
        }
      }
      Write-Host "releaseTagName: $releaseTagName"
      $releaseTag = Invoke-RestMethod -Uri 'https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/metadata.json' | Select-Object -ExpandProperty $releaseTagName
      Write-Host "$releaseTag"
      Write-Host "##vso[task.setvariable variable=releaseTag;]$releaseTag"
    displayName: Get Latest $(channel) Release Tag
    condition: and(succeeded(), not(startsWith(variables['releaseTag'], 'v')))

  - powershell: |
      ./tools/releaseBuild/vstsbuild.ps1 -ReleaseTag $(releaseTag) -Name powershell-snap-$(channel)
    displayName: Build snap $(channel)
    condition: and(succeeded(), ne(variables['$(channel)'],'no'))

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'
