parameters:
  - name: channel
    default: ''
  - name: vmImage
    default: ubuntu-18.04
  - name: release
    default: 'debug'

stages:
- stage: build_${{ parameters.channel }}
  displayName: Push - ${{ parameters.channel }}
  dependsOn: []
  jobs:
  - template: ./releaseBuildPhase.yml
    parameters:
      channel: ${{ parameters.channel }}
      vmImage: ${{ parameters.vmImage }}

- stage: Push_${{ parameters.channel }}
  displayName: Push - ${{ parameters.channel }}
  dependsOn: build_${{ parameters.channel }}
  jobs:
  - template: ./pushPhase.yml
    parameters:
      channel: ${{ parameters.channel }}
      release: ${{ parameters.release }}
