jobs:
- job: compliance
  pool:
    name: '1ES'

  displayName: Compliance

  variables:
    - name: repoFolder
      value: 'PowerShell-Snap'
    - name: repoPath
      value: $(Agent.BuildDirectory)\$(repoFolder)

  steps:
  - checkout: self
    path: $(repoFolder)
  - checkout: ComplianceRepo

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    displayName: 'Component Detection'

  - task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@1
    displayName: 'Run PoliCheck'
    inputs:
      targetArgument: $(repoPath)
      targetType: F
      optionsFC: 0
      optionsXS: 1
      optionsPE: '1|2|3|4'
      optionsHMENABLE: 0
      optionsUEPath: $(repoPath)\tools\terms\TermsExclusion.xml
    continueOnError: true

