name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
resources:
- repo: self
  clean: true

jobs:

- job: Set_Build_Name
#  displayName: Set Build Name
  condition: ne(variables['Build.Reason'], 'PullRequest')
  pool:
    name: Hosted Ubuntu 1604
  steps:
  - powershell:  Write-Host "##vso[build.updatebuildnumber]$env:BUILD_SOURCEBRANCHNAME-$env:BUILD_SOURCEVERSION-$((get-date).ToString("yyyyMMddhhss"))"
    displayName: Set Build Name for Non-PR

- template: ./phase.yml
  parameters:
    SnapChannel: stable

- template: ./phase.yml
  parameters:
    SnapChannel: preview
    queue: ubuntu-18.04
