name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
resources:
- repo: self
  clean: true

jobs:

- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - job: Set_Build_Name
      displayName: Set Build Name
      pool:
          name: Hosted Ubuntu 1604
      steps:
      - powershell:  Write-Host "##vso[build.updatebuildnumber]$env:BUILD_SOURCEBRANCHNAME-$env:BUILD_SOURCEVERSION-$((get-date).ToString("yyyyMMddhhss"))"
        displayName: Set Build Name for Non-PR

- template: ./templates/releaseBuildPhase.yml
  parameters:
    matrix:
      lts:
        channel: lts

- template: ./templates/releaseBuildPhase.yml
  parameters:
    matrix:
      stable:
        channel: stable

- template: ./templates/releaseBuildPhase.yml
  parameters:
    matrix:
      preview:
        channel: preview
