name: PR-$(System.PullRequest.PullRequestNumber)-$(Date:yyyyMMdd)$(Rev:.rr)
resources:
- repo: self
  clean: true

stages:
- ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
  - stage: prepare
    displayName: Prepare
    jobs:
    - job: Set_Build_Name
      displayName: Set Build Name
      pool:
        vmImage: ubuntu-18.04
      steps:
      - powershell:  Write-Host "##vso[build.updatebuildnumber]$env:BUILD_SOURCEBRANCHNAME-$env:BUILD_SOURCEVERSION-$((get-date).ToString("yyyyMMddhhss"))"
        displayName: Set Build Name for Non-PR

- stage: lts
  dependsOn: []
  jobs:
  - template: ./templates/releaseBuildPhase.yml
    parameters:
      channel: lts
      vmImage: ubuntu-18.04

- stage: stable
  dependsOn: []
  jobs:
  - template: ./templates/releaseBuildPhase.yml
    parameters:
      channel: stable
      vmImage: ubuntu-18.04

- stage: preview
  dependsOn: []
  jobs:
  - template: ./templates/releaseBuildPhase.yml
    parameters:
      channel: preview
      vmImage: ubuntu-18.04
