resources:
  repositories:
  - repository: self
    clean: true
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/Compliance

variables:
  - name: POWERSHELL_TELEMETRY_OPTOUT
    value: 1
  - name: runCodesignValidationInjection
    value: false

stages:
- template: ./templates/releaseBuildAndPushStage.yml
  parameters:
    channel: stable

- template: ./templates/releaseBuildAndPushStage.yml
  parameters:
    channel: preview

- template: ./templates/releaseBuildAndPushStage.yml
  parameters:
    channel: lts

- stage: virus_scan
  dependsOn:
    - build_and_push_stable
    - build_and_push_preview
    - build_and_push_lts
  jobs:
    - template: ./templates/virusScanPhase.yml
