resources:
  repositories:
  - repository: self
    clean: true
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/Compliance

variables:
  POWERSHELL_TELEMETRY_OPTOUT: 1

stages:
- template: ./templates/releaseBuildAndPushStage.yml
  parameters:
    channel: stable

- template: ./templates/releaseBuildAndPushStage.yml
  parameters:
    channel: preview

- template: ./templates/releaseBuildAndPushStage.yml
  parameters:
    channel: lts

- stage: virus_scan
  dependsOn:
    - build_and_push_stable
    - build_and_push_preview
    - build_and_push_lts
  jobs:
  - template: ./templates/virusScanPhase.yml

- stage: compliance
  displayName: Compliance
  dependsOn:
    - build_and_push_stable
    - build_and_push_preview
    - build_and_push_lts
  jobs:
  - job: Compliance_Job
      pool:
        name: 'PowerShell1ES'
      steps:
      - checkout: self
      - checkout: ComplianceRepo
