resources:
- repo: self
  clean: true

variables:
  POWERSHELL_TELEMETRY_OPTOUT: 1

stages:
- stage: build
  jobs:
  - template: ./templates/releaseBuildPhase.yml
    parameters:
      matrix:
        stable:
          channel: stable
        preview:
          channel: preview
        lts:
          channel: lts

- stage: push
  jobs:
  - template: ./templates/pushPhase.yml
    parameters:
      matrix:
        stable:
          channel: stable
        preview:
          channel: preview
        lts:
          channel: lts

- stage: virus_scan
  jobs:
  - template: ./templates/virusScanPhase.yml
