resources:
- repo: self
  clean: true

variables:
  POWERSHELL_TELEMETRY_OPTOUT: 1

stages:
- template: ./templates/releaseBuildAndPushStage.yml
  parameters:
    channel: stable

- template: ./templates/releaseBuildAndPushStage.yml
  parameters:
    channel: preview
    vmImage: ubuntu-18.04

- template: ./templates/releaseBuildAndPushStage.yml
  parameters:
    channel: lts
    vmImage: ubuntu-18.04

- stage: virus_scan
  dependsOn:
    - build_and_push_stable
    - build_and_push_preview
    - build_and_push_lts
  jobs:
  - template: ./templates/virusScanPhase.yml
