parameters:
  - name: channel
    type: string

jobs:

- job: scan
  displayName: Scan ${{ parameters.channel }}

  pool:
    type: linux

  variables:
    - name: channel
      value: ${{ parameters.channel }}
    - name: ob_outputDirectory
      value: '$(Build.ArtifactStagingDirectory)/out'
    - name: DOWNLOAD_DIRECTORY
      value: '$(Build.ArtifactStagingDirectory)/down'

  steps:
    - template: ./createOutputDirectory-linux.yml

    - task: DownloadPipelineArtifact@2
      displayName: 'Download targz files'
      inputs:
        targetPath: $(DOWNLOAD_DIRECTORY)
        artifact: drop_build_$(channel)_build_$(channel)_targz

    - pwsh: |
        $targzs = Get-ChildItem $(DOWNLOAD_DIRECTORY)/*.tar.gz -recurse -File | Select-Object -ExpandProperty FullName

        foreach($targz in $targzs)
        {
            Write-Verbose -Verbose "Extracting $targz"
            $target = '$(ob_outputDirectory)'
            tar -xvf $targz -C $target
        }
      displayName: 'Extract Tar.Gz'
