parameters:
  - name: channel
    type: string

jobs:

- job: scan
  displayName: Scan ${{ parameters.channel }}

  pool:
    type: linux

  variables:
    - name: channel
      value: ${{ parameters.channel }}
    - name: SNAP_MOUNT
      value: $(Agent.TempDirectory)/pwshSnap
    - name: SNAP_COPY
      value: $(Agent.TempDirectory)/pwshSnapCopy
    - name: SNAP_TARGZ
      value: $(Agent.TempDirectory)/pwshSnap.tar.gz
    - name: ob_outputDirectory
      value: '$(Build.ArtifactStagingDirectory)/out'
    - name: DOWNLOAD_DIRECTORY
      value: '$(Build.ArtifactStagingDirectory)/down'

  steps:
    - template: ./createOutputDirectory-linux.yml

    - task: DownloadPipelineArtifact@2
      displayName: 'Download targz files'
      inputs:
        targetPath: $(DOWNLOAD_DIRECTORY)
        artifact: drop_build_$(channel)_build_$(channel)_targz


