#!/bin/sh
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

SNAP="/snap/powershell/current"
SNAP_NAME="$(awk '/^name:/{print $2}' $SNAP/meta/snap.yaml)"
SNAP_VERSION="$(awk '/^version:/{print $2}' $SNAP/meta/snap.yaml)"
SNAP_ARCH="amd64"

export SNAP
export SNAP_NAME
export SNAP_VERSION
export SNAP_ARCH

exec "$SNAP/opt/powershell/pwsh" "$@"
