#!/bin/sh
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Create $XDG_RUNTIME_DIR if it doesn't exist
[ -n "$XDG_RUNTIME_DIR" ] && mkdir -p $XDG_RUNTIME_DIR -m 700

exec "$SNAP/opt/powershell/pwsh" "$@"
