#!/bin/sh
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# never use a customer specified .NET runtime
unset DOTNET_ROOT

exec "$SNAP/opt/powershell/pwsh" "$@"
