name: powershell
version: 6.0.1
version-script: |
  file="./version.txt"
  if [ -f "$file" ]
  then
    cat ./version.txt
  else
    version=$(curl -s 'https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/metadata.json' | jq .ReleaseTag | sed 's/"//g' | sed 's/v//')
    $version > ./version.txt
    echo $version
  fi
summary: PowerShell for every system
description: |
  PowerShell is an automation and configuration management platform.
  It consists of a cross-platform (Windows, Linux and macOS)
  command-line shell and associated scripting language.

confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  powershell:
    command: opt/powershell/pwsh
  # powershell:
  #   command: bin/powershell-launch
  # telemetry:
  #   command: bin/powershell-telemetry

parts:
  patches:
    plugin: dump
    source: patches
    prime: [-*]

  scripts:
    plugin: dump
    source: scripts
    prepare: |
      chmod +x powershell-launch powershell-telemetry
    organize:
      '*': bin/

  powershell:
    # after: [scripts]
    # plugin: dump
    # source: https://github.com/PowerShell/PowerShell/releases/download/v6.0.0/powershell_6.0.0-1.ubuntu.16.04_amd64.deb
    after: [scripts, patches]
    plugin: nil
    prepare: |
      version=$(cat ./version.txt)
      echo getting powershell $version
      curl -L -o powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v$version/powershell-$version-linux-x64.tar.gz
    # patch -Np1 < "$SNAPCRAFT_STAGE/telemetry.diff"
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/powershell
      tar zxf powershell.tar.gz -C $SNAPCRAFT_PART_INSTALL/opt/powershell
      chmod +x $SNAPCRAFT_PART_INSTALL/opt/powershell/pwsh
    stage-packages:
      - libcurl3
      - libicu55
      - liblttng-ust0
      - libssl1.0.0
      - libunwind8
      - libuuid1
      - zlib1g
    build-packages:
      - curl
      - jq
