name: powershell

# the version number is not used, but required
version: 6.0.1
version-script: |
  file="./version.txt"
  if [ -f "$file" ]
  then
    cat $file
  else
    version=$(curl -s 'https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/metadata.json' | jq .ReleaseTag | sed 's/"//g' | sed 's/v//')
    echo $version
  fi
summary: PowerShell for every system
description: |
  PowerShell is an automation and configuration management platform.
  It consists of a cross-platform (Windows, Linux and macOS)
  command-line shell and associated scripting language.

confinement: classic

apps:
  powershell:
    command: opt/powershell/pwsh

parts:
  patches:
    plugin: dump
    source: patches
    prime: [-*]

  scripts:
    plugin: dump
    source: scripts
    prepare: |
      chmod +x powershell-launch powershell-telemetry
    organize:
      '*': bin/

  powershell:
    after: [scripts, patches]
    plugin: nil
    prepare: |
      file="./version.txt"
      if [ -f "$file" ]
      then
        echo using version file
        version=$(cat $file)
      else
        echo getting latest version from GitHub
        version=$(curl -s 'https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/metadata.json' | jq .ReleaseTag | sed 's/"//g' | sed 's/v//')
        echo Writing version to file
        echo $version > $file
      fi
      echo getting powershell $version
      curl -L -o powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v$version/powershell-$version-linux-x64.tar.gz
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/powershell
      tar zxf powershell.tar.gz -C $SNAPCRAFT_PART_INSTALL/opt/powershell
      chmod +x $SNAPCRAFT_PART_INSTALL/opt/powershell/pwsh
    stage-packages:
      - libcurl3
      - libicu55
      - liblttng-ust0
      - libssl1.0.0
      - libunwind8
      - libuuid1
      - zlib1g
    build-packages:
      - curl
      - jq
